# /*------------------------------------------------------------\
# |                                                             |
# | File   :                    Makefile                        |
# |                                                             |
# | Author :                 Jacomme Ludovic                    |
# |                                                             |
# \------------------------------------------------------------*/
# /*------------------------------------------------------------\
# |                                                             |
# |                              Cells                          |
# |                                                             |
# \------------------------------------------------------------*/
# /*------------------------------------------------------------\
# |                                                             |
# |                             Binary                          |
# |                                                             |
# \------------------------------------------------------------*/

FILENAME=led_top
FILETYPE=gds

#CORE=$(FILENAME)
CORE=core_top

CHIP=chip64

SRCDIR=.
VPATH=$(SRCDIR)/:$(SRCDIR)/../src:$(SRCDIR)/chip_layout

USERTOOLS=../../etc
USERCELL_TOP=$(USERTOOLS)/cells
USERRDS=$(USERTOOLS)/rds


NETLISTS = 
NETLISTS_VST=$(foreach netlist,$(NETLISTS), $(netlist).vst)

i=1
ALLIANCE_BIN=$(ALLIANCE_TOP)/bin
#ALLIANCE4_BIN=$(ALLIANCE4_TOP)/bin
ALLIANCE4_BIN=/opt/alliance-4.0-patched/archi/Linux/bin

VASY   = $(ALLIANCE_BIN)/vasy
ASIMUT = $(ALLIANCE_BIN)/asimut
BOOM   = $(ALLIANCE_BIN)/boom
BOOG   = $(ALLIANCE_BIN)/boog
LOON   = $(ALLIANCE_BIN)/loon
OCP    = $(ALLIANCE_BIN)/ocp
NERO   = $(ALLIANCE_BIN)/nero
COUGAR = $(ALLIANCE_BIN)/cougar
LVX    = $(ALLIANCE_BIN)/lvx
DRUC   = $(ALLIANCE_BIN)/druc
S2R    = $(ALLIANCE_BIN)/s2r
RING   = $(ALLIANCE_BIN)/ring
SCMAP  = $(ALLIANCE4_BIN)/scmap
SCR    = $(ALLIANCE4_BIN)/scr

DREAL  = $(ALLIANCE_BIN)/dreal
GRAAL  = $(ALLIANCE_BIN)/graal
XSCH   = $(ALLIANCE_BIN)/xsch
XPAT   = $(ALLIANCE_BIN)/xpat
XFSM   = $(ALLIANCE_BIN)/xfsm

TOUCH  = touch

TARGET_LIB      = $(ALLIANCE_TOP)/cells/sxlib
#CATA_LIB	= $(USERCELL_TOP)/h24umlib:$(ALLIANCE_TOP)/cells/sxlib:$(ALLIANCE_TOP)/cells/padlib
CATA_LIB	= $(USERCELL_TOP)/h24umlib:$(ALLIANCE_TOP)/cells/sxlib:$(USERCELL_TOP)/padlib
RDS_TECHNO		= $(USERRDS)/h24um.rds
METAL_LEVEL     = 2

LO_NUM			= 5

NSL2VHOPT = -vasy -split -O2 -DLSI

# /*------------------------------------------------------------\
# |                                                             |
# |                            Environement                     |
# |                                                             |
# \------------------------------------------------------------*/

MBK_WORK_LIB	= .
MBK_IN_LO	= vst
MBK_OUT_LO	= vst
MBK_IN_PH	= ap
MBK_OUT_PH	= ap
MBK_TARGET_LIB	= $(TARGET_LIB)
MBK_CATAL_NAME	= CATAL
MBK_CATA_LIB	= $(CATA_LIB)
MBK_VDD		= vdd
MBK_VSS		= vss
VH_MAXERR	= 10
VH_BEHSFX	= vbe
VH_PATSFX	= pat
VH_DLYSFX	= dly
RDS_IN		= gds
RDS_OUT		= gds

RING_WMIN_ALU1 = 2
RING_WMIN_ALU2 = 2
RING_DMIN_ALU1_ALU1 = 2
RING_DMIN_ALU2_ALU2 = 2
RING_WVIA_ALU1 = 3
RING_EXTENSION_ALU2 = 6

RDS_TECHNO_NAME	= $(RDS_TECHNO)
GRAAL_TECHNO_NAME=$(ALLIANCE_TOP)/etc/cmos.graal
DREAL_TECHNO_NAME= h24um.dreal



MODELNAME = $(FILENAME)_model

ENV_ALL = export MBK_WORK_LIB=$(MBK_WORK_LIB);\
	export MBK_TARGET_LIB=$(MBK_TARGET_LIB);\
	export MBK_CATA_LIB=$(MBK_CATA_LIB);\
	export MBK_IN_PH=$(MBK_IN_PH);\
	export MBK_OUT_PH=$(MBK_OUT_PH);\
	export MBK_IN_LO=$(MBK_IN_LO);\
	export MBK_OUT_LO=$(MBK_OUT_LO);\
	export MBK_VDD=$(MBK_VDD);\
	export MBK_VSS=$(MBK_VSS);\
	export RDS_IN=$(RDS_IN);\
	export RDS_OUT=$(RDS_OUT);\
	export DREAL_TECHNO_NAME=$(DREAL_TECHNO_NAME);\
	export RDS_TECHNO_NAME=$(RDS_TECHNO);\
	export MBK_CATAL_NAME=$(MBK_CATAL_NAME)

ENV_RING= $(ENV_ALL);\
	export RING_WMIN_ALU1=$(RING_WMIN_ALU1);\
	export RING_WMIN_ALU2=$(RING_WMIN_ALU2);\
	export RING_WVIA_ALU1=$(RING_WVIA_ALU1);\
	export RING_DMIN_ALU1_ALU1=$(RING_DMIN_ALU1_ALU1);\
	export RING_DMIN_ALU2_ALU2=$(RING_DMIN_ALU2_ALU2);\
	export RING_EXTENSION_ALU2=$(RING_EXTENSION_ALU2)


ENV_COUGAR = $(ENV_ALL);\
	export MBK_OUT_LO=al

ENV_LVX= $(ENV_ALL)



all :  $(FILENAME).$(FILETYPE)


%.vhdl: %.nsl
	nsl2vh $(NSL2VHOPT) $<

# /*------------------------------------------------------------\
# |                                                             |
# |                             Vasy                            |
# |                                                             |
# \------------------------------------------------------------*/

#vasy.done : $(FILENAME).vhdl
	#$(ENV_VASY); $(VASY) -a -o -p -H -I vhdl $(FILENAME)

%.vbe	: %.vhdl
	$(ENV_ALL); $(VASY) -a -p -I vhdl $*


# /*------------------------------------------------------------\
# |                                                             |
# |                             SCMAP                           |
# |                                                             |
# \------------------------------------------------------------*/

#%.vst : %.vbe
#	$(ENV_ALL);$(SCMAP) $* $*

# /*------------------------------------------------------------\
# |                                                             |
# |                             BOOM                            |
# |                             BOOG                            |
# |                                                             |
# \------------------------------------------------------------*/

%.vst : %.vbe
	$(ENV_ALL);$(BOOM) $*
	$(ENV_ALL);$(BOOG) $*_o $*

%_model.vst : %.vbe
	$(ENV_ALL);$(BOOM) $*_model
	$(ENV_ALL);$(BOOG) $*_model_o $*_model

# /*------------------------------------------------------------\
# |                                                             |
# |                             SCR                             |
# |                                                             |
# \------------------------------------------------------------*/


#%.ap : %.vst  $(FILENAME)_model.vst
%.ap : %.vst  $(FILENAME).vst
	$(ENV_ALL); $(SCR) -l $(LO_NUM) -p -r i 1000 $* $*

# /*------------------------------------------------------------\
# |                                                             |
# |                             S2R                             |
# |                                                             |
# \------------------------------------------------------------*/

%.gds : %.ap
	$(ENV_ALL); $(S2R) $*

check :
	$(ENV_S2R); $(S2R) nr3abv0x05

# /*------------------------------------------------------------\
# |                                                             |
# |                             RING                            |
# |                                                             |
# \------------------------------------------------------------*/

#$(CHIP).ap:$(CHIP).vst $(CORE).vst $(CORE).ap
#$(CHIP).ap:$(CHIP).vst $(CORE)_model.vst $(CORE).ap
#$(CHIP).ap:$(CHIP).vst $(CORE).ap $(FILENAME)_model.vst
$(CHIP).ap:$(CHIP).vst $(CORE).ap
	cp $(SRCDIR)/chip_layout/$(CHIP).rin ./
	cp $(SRCDIR)/chip_layout/$(CHIP).vst ./
	$(ENV_RING); $(RING) $(CHIP) $(CHIP)


# /*------------------------------------------------------------\
# |                                                             |
# |                             Asimut                          |
# |                                                             |
# \------------------------------------------------------------*/

$(FILENAME)_as.pat : $(FILENAME).pat $(FILENAME)_n.ap
	$(ENV_ASIMUT); $(ASIMUT) $(FILENAME)_ln $(FILENAME) $(FILENAME)_as

# /*------------------------------------------------------------\
# |                                                             |
# |                             Cougar                          |
# |                                                             |
# \------------------------------------------------------------*/

%_c.al : %.ap 
	$(ENV_COUGAR); $(COUGAR) -v -f $* $*_c

# /*------------------------------------------------------------\
# |                                                             |
# |                             Druc                            |
# |                                                             |
# \------------------------------------------------------------*/

druc : $(FILENAME).ap
	$(ENV_ALL); $(DRUC) $(FILENAME)

# /*------------------------------------------------------------\
# |                                                             |
# |                             Lvx                             |
# |                                                             |
# \------------------------------------------------------------*/

#$(FILENAME)_c.vst : $(FILENAME)_ln.vst $(FILENAME)_c.al $(FILENAME).drc

#$(CORE)_c.vst : $(CORE).vst $(CORE)_c.al 
%_c.vst : %.vst %_c.al 
	$(ENV_LVX); $(LVX) vst al $* $*_c -a -o -f

%.lvx : %_c.al
	$(ENV_LVX); $(LVX) vst al $* $*_c -a -o -f


# /*------------------------------------------------------------\
# |                                                             |
# |                             TOOLS                           |
# |                                                             |
# \------------------------------------------------------------*/

graal :
	$(ENV_ALL); $(GRAAL)

xsch:
	$(ENV_LOON); $(XSCH)

xsch_$(FILENAME)_o : $(FILENAME).vst
	$(ENV_LOON); $(XSCH) -l $(FILENAME)_o

xsch_$(FILENAME) : $(FILENAME).vst
	$(ENV_LOON); $(XSCH) -l $(FILENAME)

xsch_$(FILENAME)_e: $(FILENAME)_e.al
	$(ENV_COUGAR); $(XSCH) -l $(FILENAME)_e

xsch_$(FILENAME)_et: $(FILENAME)_et.al
	$(ENV_COUGAR); $(XSCH) -l $(FILENAME)_et

xpat: 
	$(ENV_ASIMUT_SYNTH); $(XPAT)

xpat_synth: res_synth_1.pat
	$(ENV_ASIMUT_SYNTH); $(XPAT) -l res_synth_1

xpat_vasy : res_vasy_1.pat
	$(ENV_ASIMUT_SYNTH); $(XPAT) -l res_vasy_1

dreal_sym: 
	$(ENV_DRUC); $(DREAL)

dreal: 
	$(ENV_ALL); $(DREAL)

dreal-gdb: 
	$(ENV_ALL); gdb $(DREAL)

dreal_$(FILENAME) :
	$(ENV_S2R); $(DREAL) -l $(FILENAME)_n

x2y : $(MODELNAME).vst
	export MBK_IN_LO=edi; x2y vst edi $(FILENAME) $(FILENAME)

# /*------------------------------------------------------------\
# |                                                             |
# |                              Clean                          |
# |                                                             |
# \------------------------------------------------------------*/

realclean : clean

clean     :
	$(RM) -f *.vhdl $(FILENAME).vst $(FILENAME)_model.vst $(FILENAME)_e.spi $(FILENAME)_et.spi *.vbe res_*.pat *.boom *.done *.xsc *.gpl \
                 *.ap *.drc *.dat *.cif *.rep \
		 *.log *.out *.raw *.al *.tmp *.gds *_c.vst *_c.al
